name: 'AI Issue and Comment Moderator'
description:
  'Scan new issues and comments with GitHub Models AI prompts; label or hide
  spam automatically.'
author: 'GitHub'
branding:
  icon: 'shield'
  color: 'purple'

inputs:
  token:
    description:
      'GitHub token with `issues`, `pull-requests`, and `models: read`
      permissions'
    required: false
    default: ${{ github.token }}
  spam-label:
    description: 'Label to add when generic spam is detected'
    required: false
    default: 'spam'
  ai-label:
    description: 'Label to add when AI-generated content is detected'
    required: false
    default: 'ai-generated'
  minimize-detected-comments:
    description: 'Whether to minimize comments detected as spam'
    required: false
    default: 'true'
  custom-prompt-path:
    description:
      'Path to a custom YAML prompt file in your repository (relative to
      repository root)'
    required: false
  enable-spam-detection:
    description: 'Enable built-in spam detection prompt'
    required: false
    default: 'true'
  enable-link-spam-detection:
    description: 'Enable built-in link spam detection prompt'
    required: false
    default: 'true'
  enable-ai-detection:
    description: 'Enable built-in AI-generated content detection prompt'
    required: false
    default: 'true'

runs:
  using: 'node24'
  main: 'dist/index.js'
